name = "MapSlide"
uuid = "4835d68d-66a2-4400-9ee5-7d9b7f25dca9"
keywords = ["sliding", "rolling", "running", "moving", "window", "timeseries"]
license = "MIT"
desc = "Like mapslices for sliding windows"
authors = ["Kevin Patel", "Jeffrey Sarnoff", "et al."]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
